buildkite/test-collector-python

CODE_OF_CONDUCT.md
Hi, we would like to introduce Code of Conduct document for all Buildkite open source repositories (based on [Contributor Covenant v2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)). Thank you!
=> Add CODE_OF_CONDUCT document

README.md, setup.py
Addressing the github issue raised here: https://github.com/buildkite/test-collector-python/issues/5
Explicitly documenting the python versions supported are >=3.8  and setting `python_requires=">=3.8"` in `setup.py`
=> Add python_requires >=3.8 to setup.py and README

setup.py, src/buildkite_test_collector/collector/api.py, tests/buildkite_test_collector/collector/test_api.py
It's important that the collector doesn't break customer builds. If the buildkite api token includes a return character (i.e., \r or \n) the Python libraries throw an InvalidHeader exception, which would cause the process to error out. This patch gracefully handles the error so the customer's test suite doesn't fail.
=> Gracefully handle return characters in api token

setup.py, src/buildkite_test_collector/collector/constants.py, src/buildkite_test_collector/collector/run_env.py, tests/buildkite_test_collector/collector/test_run_env.py
TA is working on displaying a tally of the types of collectors our customers are using. We can gather this data via the collector names and versions, however some collectors are missing this data (please see related linear ticket for list).
As I am unfamilar with python, I moved the NAME and VERSION values from the `setup.py` and defined them in a new file `constants.py`. This way we can share these values across file names while keeping them consistent. Happy to change if a Python speaker knows better!
This PR does not include the necessary version bump + publish to Python Package Index.
This collector will now emit the collector name "**python-buildkite-test-collector**"
-----
[Linear Ticket](https://linear.app/buildkite/issue/PIE-1353/add-collector-name-and-version-to-python-test-collec …
=> Add Collector name and version to Analytics API payload

src/buildkite_test_collector/collector/constants.py, src/buildkite_test_collector/collector/run_env.py, tests/buildkite_test_collector/collector/test_run_env.py
```
{"buildkite-test_collector"=>79,
"js-buildkite-test-collector"=>58,
"test-collector-buildkite-plugin"=>52,
"rspec-buildkite"=>5,
nil=>94,
"python-{COLLECTOR_NAME}"=>4, <----- 💥 rage 💥
"test-collector-swift"=>2,
"js-integration"=>1}
```
Discovered that string interpolation involves a 'f' special key and double quotes in python.
=> [PIE-1353]: Update python collector

src/buildkite_test_collector/collector/payload.py, src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, tests/buildkite_test_collector/collector/test_payload.py, tests/buildkite_test_collector/conftest.py
**Description**
We have removed identifier field from DB test table, and we no longer using it in TA.
This PR is for removing identifier from this collector so that they stop sending identifier to TA. [We'll not make a release for this PR](https://linear.app/buildkite/issue/PIE-1427#comment-9ea47561)
**Context**
Ticket: https://linear.app/buildkite/issue/PIE-1480/remove-identifier-from-python-test-collector-payloads
Parent ticket: https://linear.app/buildkite/issue/PIE-1427/remove-identifier-from-test-collector-payloads
**Changes**
Remove identifier from payload
Update tests
=> PIE-1480 Remove identifier from Python test collector payloads

src/buildkite_test_collector/collector/api.py, tests/buildkite_test_collector/collector/test_api.py
Linear ticket: [https://linear.app/buildkite/issue/PIE-1486/python-collector-shouldnt-fail-customer-builds](https://linear.app/buildkite/issue/PIE-1486/python-collector-shouldnt-fail-customer-builds)
There was an incident affecting the main database, and as a result TA was timing out. The TA timeouts then caused a customer's builds to break which is bad.
Changes:
- introduced catch all for exceptions in `submit` so we don't fail builds if there is a `ReadTimeout` or a `ConnectTimeout`
- added specs to cover those two exceptions
Future plans:
- will probably add retries for `ReadTimeout` and `ConnectTimeout`
=> [PIE-1486] python collector shouldn't fail customer builds

README.md
This PR provides more information about how to get span tracing for Python up and running in Test Analytics.
It includes:
- More background into how tracing works in Buildkite Test Analytics collectors generally
- Links through to examples in our [reference test collector implementation in Ruby](https://github.com/buildkite/test-collector-ruby)
- A link directly to the relevant part of code to see `SpanCollector` documentation
I don't have experience in Python, so if anything here doesn't make sense in a Python context, I would appreciate an edit! 🙇🏻‍♀️
=> Add more information in README about span tracing

src/buildkite_test_collector/pytest_plugin/__init__.py
Similar to https://github.com/buildkite/test-collector-python/issues/7 it would be great for the plugin to honour the `BUILDKITE_ANALYTICS_DEBUG_ENABLED` env variable and be less verbose by default.
=> Silence warning unless debug is present

.github/workflows/python.yaml, src/buildkite_test_collector/pytest_plugin/__init__.py
The way xdist works is somewhat surprising:
- one might expect a single pytest execution, however all workers run the full pytest lifecycle as well as the main controller process resulting in `n+1` pytest executions (where `n` is the actual number of workers)
- the workers also swallow stdout so introspecting this was producing misleading results when trying to reproduce locally (see this thread for more info https://github.com/pytest-dev/pytest-xdist/issues/354)
This checks that we're in the controller process (eg the existence of "workerinput" implies an xdist worker thread), and only submits the results payload if we're in the controller or `master` process.
The JUnit test reporter has a range of other strategies to deal with xdist but this particular check inspired this fix …
=> Check we're not in an xdist worker before submitting payload

src/buildkite_test_collector/collector/run_env.py, tests/buildkite_test_collector/collector/test_run_env.py
Fixes: #31.
(I chose `TEST_ANALYTICS_` prefix because I didn't want to confuse users of GHA or Circle into thinking that the env-var was a native-to-their-platform one then not find it within docs)
=> Add TEST_ANALYTICS_COMMIT_MESSAGE

src/buildkite_test_collector/collector/api.py, tests/buildkite_test_collector/collector/test_api.py
Make the upload API URL configurable via a `BUILDKITE_ANALYTICS_API_URL` environment variable.
This is mostly useful for local development / debugging.
=> `BUILDKITE_ANALYTICS_API_URL` for configurable upload API endpoint

src/buildkite_test_collector/collector/payload.py, src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, tests/buildkite_test_collector/collector/test_payload.py, tests/buildkite_test_collector/conftest.py
Add `file_name` to test payload as it is currently missing.
Reference: https://buildkite.com/docs/test-engine/importing-json#json-test-results-data-reference-test-result-objects
=> Add `file_name` to test payload

.buildkite/pipeline.release.yml, .buildkite/steps/release-pypi, README.md
* Slightly revamp the doc on releasing this tool.
* Add CD code for automatic deployment.
=> PIE-3516 part 1: get ready to use CD pipeline

src/buildkite_test_collector/pytest_plugin/__init__.py, src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, tests/buildkite_test_collector/pytest_plugin/test_plugin.py
We’re integrating [bktec](https://github.com/buildkite/test-engine-client) with pytest, which requires reading the output from pytest. While pytest has native JUnit XML, it lacks certain information required by `bktec`. Since `bktec` relies on this collector, it’s more convenient to save the JSON output from this collector, so `bktec` can read it.
To save json payload to a file, you need to add `--json=path` option to the `pytest command`. For example
```
pytest --json=result.json
```
=> Add `--json` option to save collector payload to JSON

.buildkite/pipeline.release.yml, README.md
* After clarifying with other engineers, I replace Buildkite Secret with AWS SSM. 
* I also tweak the release flow so it's much simplified. 
If this is successful, we can probably apply the same practice to other Test Engine open source repos.
=> PIE-3516 part 2: use AWS SSM instead and simplify the release workflow

.buildkite/pipeline.release.yml
For some reason, the SSM plugin will just fail silently demanding a region setting. 
I think it must be because that we are using hosted agent. This PR should fix it.
=> PIE-3516 follow up 2: force AWS region

src/buildkite_test_collector/collector/payload.py, src/buildkite_test_collector/pytest_plugin/__init__.py, src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, tests/buildkite_test_collector/collector/test_payload.py
Add execution level tagging using `execution_tag` custom marker. The test collector will send all tags marked on each test to Buildkite Test Engine. See pytest's [custom markers ](https://docs.pytest.org/en/stable/example/markers.html)documentation.
tagging individual tests using decorator:
```py
import pytest
@pytest.mark.execution_tag("key", "value")
@pytest.mark.execution_tag("another.key", "value")
def test_add():
assert 1 + 1 == 2
```
tagging all tests in a test class using decorator:
```py
import pytest
@pytest.mark.execution_tag("key", "value")
@pytest.mark.execution_tag("another.key", "value")
class TestSubstract:
def test_positive(self):
assert 5 - 4 == 1
def test_negative(self):
assert 2 - 3 = -1 
```
tagging all tests in a module using `pytestmark` helper
```py
import pytest …
```
=> Add execution level tagging

src/buildkite_test_collector/collector/run_env.py, src/buildkite_test_collector/pytest_plugin/__init__.py, tests/buildkite_test_collector/collector/test_run_env.py
Currently, the test collector doesn’t function if the `CI` environment is missing. Since there’s no compelling reason to requires a `CI` environment for running the test collector, we can remove these restrictions.
=> Remove `CI` environment requirement

.editorconfig, .gitignore, src/buildkite_test_collector/collector/api.py, src/buildkite_test_collector/collector/constants.py, src/buildkite_test_collector/pytest_plugin/__init__.py, src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, src/buildkite_test_collector/pytest_plugin/logger.py, tests/buildkite_test_collector/collector/test_api.py
We had one report of Test Result upload contains empty data. User claimed that this only started happening since `v1.0.0`. 
I couldn't not reproduce the same issue (using the same pytest version) so I had to make a logical guess:
* The fact that upload works means our plugin is successfully loaded. 
* The fact that `v0.2.0` works means there is no problem in our `pytest_runtest_logreport ` hook (v1 introduced `pytest_runtest_teardown` hook to collect test, v0.2 relies solely on `pytest_runtest_logreport`). 
* So my guess is that something prevent `pytest_runtest_teardown` from running. 
---
So I added lots of debug logging, user can opt-in to seeing them by setting env var `DEBUG=1`. 
I also add some a defensive mechanism: another `pytest_runtest_logfinish` hook hoping as a fallback …
=> [release] 1.0.1rc1: more logs and defensive mechanism for test collection

src/buildkite_test_collector/collector/constants.py, src/buildkite_test_collector/collector/payload.py, src/buildkite_test_collector/collector/run_env.py, src/buildkite_test_collector/pytest_plugin/__init__.py, src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, src/buildkite_test_collector/pytest_plugin/logger.py
We discovered that `xdist` doesn't work with our `1.0.0` version, the reason can be summarize in one sentence: when xdist is enabled, some hooks will get totally ignored. 
But the fix is not so simple, because there isn't an official document saying which hooks will be skipped under what situation. So after a lot of experiments, I come to the following change: 
* use `pytest_runtest_makereport` to replace `pytest_runtest_teardown` hook (this gets totally skipped by `xdist`). 
* When xdist is activated, use worker thread to upload test result so we can read tags.  
* Add extra logging for unfinished test data situation.
* As a side change, I went back to using `BUILDKITE_ANALYTICS_DEBUG_ENABLED` as debug envvar instead of the general `DEBUG` env var.
I have tested extensively in my local …
=> [release] 1.0.1rc2: support xdist properly

src/buildkite_test_collector/collector/api.py, src/buildkite_test_collector/pytest_plugin/__init__.py, tests/buildkite_test_collector/collector/test_api.py
This was returning early meaning only the first batch was being submitted. This caused truncation in test collection for large test suites.
=> Fix batch submission

setup.py, src/buildkite_test_collector/collector/payload.py, src/buildkite_test_collector/pytest_plugin/__init__.py, src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, tests/buildkite_test_collector/pytest_plugin/test_plugin.py
This feature is related to adding pants support to [test-engine-client](https://github.com/buildkite/test-engine-client) (i.e. https://github.com/buildkite/test-engine-client/pull/323)
=> add --merge-json cli flag to support bktec and pants

src/buildkite_test_collector/collector/api.py, src/buildkite_test_collector/collector/run_env.py, src/buildkite_test_collector/pytest_plugin/__init__.py, tests/buildkite_test_collector/collector/test_api.py, tests/buildkite_test_collector/collector/test_payload.py, tests/buildkite_test_collector/collector/test_run_env.py
Two parts of this collector need to access environment variables:
- `RunEnv` uses it to discover & construct `run_env` (CI environment details e.g. build message)
- `submit()` uses it to get API key/URL.
Previously we were reaching into `os.environ` throughout the code, and mocking it in tests like this:
```python
with mock.patch.dict(os.environ, {"CI": "true", "BUILDKITE_ANALYTICS_TOKEN": ""}):
```
Now, we wrap those environment accesses behind a `Mapping[str, Optional[str]]` type; real code passes in `os.environ`, and tests pass in an arbitrary dict.
Diff best viewed with whitespace ignored, there's quite a bit of indentation change from removing the `with mock…:` blocks.
Related:
- Stacked on #60
=> Abstract `os.environ` so real env doesn't interfere with tests

README.md, src/buildkite_test_collector/collector/api.py, src/buildkite_test_collector/collector/payload.py
Update README and comments to refer to Test Engine, not Test Analytics.
=> `s/Test Analytics/Test Engine/g`

.github/workflows/python.yaml, README.md, pyproject.toml, uv.lock
Python 3.8 EOL was 2024-10-07, so remove support.
Python 3.9 will EOL in a couple of months and will also be removed then.
Related:
- https://devguide.python.org/versions/#versions
- https://peps.python.org/pep-0569/
=> Python 3.8 no longer supported; EOL was 2024-10-07

src/buildkite_test_collector/collector/payload.py, src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, src/buildkite_test_collector/pytest_plugin/failure_reasons.py, tests/buildkite_test_collector/collector/test_payload.py, tests/buildkite_test_collector/conftest.py, tests/buildkite_test_collector/pytest_plugin/test_plugin.py
Currently, the entire failure from PyTest (PyTest calls it `longreprtext`) is set as `failure_reason`.
However, `failure_reason` is intended for a short one-line summary, and gets truncated to ~1KIB, which isn't great for `longreprtext`.
Buildkite also supports `failure_expanded`, for including detailed information and backtraces on errors.
So, derive that from the various shapes that `longrepr` can take, and include them in the uploaded JSON payload.
| Before | After |
|--------|--------|
| Unclear `failure_reason` summaries:<br> <img width="981" height="278" alt="image" src="https://github.com/user-attachments/assets/d7df9ecf-2581-4135-ad7b-f76c55066dbc" /> | Useful failure/error messages:<br> <img width="967" height="273" alt="image" …
=> Clearer failure/errors in `failure_reason` & `failure_expanded`

src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, tests/buildkite_test_collector/pytest_plugin/test_plugin.py
Currently, errors during `setup` (e.g. fixtures) cause a result of `unknown` without any error/failure information.
For example:
```python
import pytest
@pytest.fixture
def greeting():
return "hello" + 1 # TypeError: can only concatenate str (not "int") to str
def test_with_fixture(greeting):
assert greeting == "hello"
```
Because the `setup` phase failed, the `call` phase never runs, and so the assertion never runs.
This pull request adds handling for `report.when == 'setup' and report.failed`, which captures this scenario.
Related:
- Stacked on #64 
- https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.hookspec.pytest_runtest_protocol
=> Handle failure in `setup` eg fixtures

src/buildkite_test_collector/collector/run_env.py, src/buildkite_test_collector/pytest_plugin/buildkite_plugin.py, tests/buildkite_test_collector/collector/test_run_env.py
To collect Python language version usage and help us to better
plan deprecation support of end-of-life Python versions.
=> [TE-4096] Add 'language_version' attribute to env var
